### ISSUE TITLE
Fix Tips icon

### ISSUE THREAD

**Issue by JosephineAkello** [Tambua-WomenInTech-Blog/womenintechblog#32]
![Screenshot-from-2021-07-10-17-34-02](https://user-images.githubusercontent.com/39112051/125166727-97595680-e1a5-11eb-9b95-56d5a4fe711a.png)

Fix the pencil icon to show the icon instead of the writing .
@cesswairimu would you please pick this up?

**Comment by cesswairimu** [comment]
oh weird that didn't work!..fixing...thanks

**Comment by cesswairimu** [comment]
###  Tips :memo:

**Comment by cesswairimu** [comment]
Opened a PR https://github.com/Tambua-WomenInTech-Blog/womenintechblog/pull/34
Thanks @JosephineAkello
