### ISSUE TITLE
Bio Images being rendered weirdly

### ISSUE THREAD

**Issue by JosephineAkello** [Tambua-WomenInTech-Blog/womenintechblog#36]
Bio profile images are rendered weirdly out of the circular border

![Screenshot from 2021-08-05 23-50-51](https://user-images.githubusercontent.com/39112051/128419633-d26da163-0d52-4b64-aec4-1f2fcff3cb22.png)
![Screenshot from 2021-08-05 23-51-10](https://user-images.githubusercontent.com/39112051/128419635-111e1978-111d-4c6a-b64f-dfeb448c260b.png)

@TheBeachMaster Is there specific image size recommendation for this issue?

**Comment by TheBeachMaster** [comment]
Interesting ... 🤔 

I'll investigate

**Comment by TheBeachMaster** [comment]
Yes , use this tool  [picresize.com](https://picresize.com/) to crop your avatars  to `512px by 512px` -px is `pixels` ... I'll update blog

**Comment by JosephineAkello** [comment]
@TheBeachMaster  Alright thank you,  creating a fix to resize the existing ones

**Comment by JosephineAkello** [comment]
@TheBeachMaster This recommendation doesn't seem to be working. The images are still rendered weirdly :thinking:

**Comment by TheBeachMaster** [comment]
![Screenshot 2021-08-22 at 13 47 46](https://user-images.githubusercontent.com/9129843/130352366-47590cdb-1a5f-4045-88d3-7dc41f0d957b.png)
They look okay 🤔

**Comment by JosephineAkello** [comment]
@TheBeachMaster This is after doing the cropping fix...using 512 by 512 px didn't work well for those specific images

**Comment by TheBeachMaster** [comment]
I'll see 🤔

**Comment by JosephineAkello** [comment]
@TheBeachMaster will close this since was fixed
