### ISSUE TITLE
specify packages installation guide per OS[nice to have]

### ISSUE THREAD

**Issue by JosephineAkello** [Tambua-WomenInTech-Blog/womenintechblog#39]
It's nice to have OS specific yarn/npm packages installation guides in the Get started Guide as well.

https://tambua-womenintech-blog.github.io/womenintechblog/How-to-add-a-blog

cc: @TheBeachMaster

**Comment by TheBeachMaster** [comment]
Which ones?

I don't get it 🤔

**Comment by JosephineAkello** [comment]
In this section, it would be nice to specify which OS to run these sets of commands and maybe how to do the same in MacOS or something and also some prerequisites for instance should one have Gatsby installed etc..

<img width="902" alt="Screenshot 2021-11-25 at 19 43 10" src="https://user-images.githubusercontent.com/39112051/143478596-8643d0dd-e1e9-423b-9a4d-bed6a814956f.png">

**Comment by TheBeachMaster** [comment]
The commands are the same irrespective of the OS

**Comment by TheBeachMaster** [comment]
https://github.com/Tambua-WomenInTech-Blog/womenintechblog/blob/d28cd405488246c92e3a5c0849e12aef7ef2d7d5/Dockerfile#L2

**Comment by JosephineAkello** [comment]
closing the issue as Not needed anymore, I guess.
